import React from "react";
import { Text, FlexBox, Box } from "~/components/atoms";
import { CryptoInvestmentTrackerLayout } from "~/components/Layout";
const PrivacyPolicy = () => {
  return (
    <CryptoInvestmentTrackerLayout>
      <FlexBox
        flexDirection="column"
        alignItems="center"
        justifyContent="top"
        height={"90vh"}
        padding={2}
        overflow={"scroll"}
      >
        <Box mb={4}>
          <Text as="h1" textAlign={"center"}>
            Privacy Policy
          </Text>
          <Text maxWidth={"600px"} textAlign={"justify"}>
            Introduction
            <br />
            Crypto Investment Tracker (&quot;we&quot;, &quot;us&quot;, or
            &quot;our&quot;) respects your privacy and is committed to
            protecting your personal data. This Privacy Policy will inform you
            about how we collect, use, and safeguard your personal data when you
            use our application and website (collectively, the
            &quot;Services&quot;).
            <br />
            <br />
            Information We Collect
            <br />
            We collect personal information from you when you use our Services,
            such as:
            <br />
            - Account information: When you create an account with us, we may
            collect your name, email address, and other relevant information.
            <br />
            - Usage information: We collect information about your usage of our
            Services, such as your investment data, portfolio details, and
            preferences.
            <br />
            <br />
            How We Use Your Information
            <br />
            We use your information for various purposes, including:
            <br />
            - Providing and maintaining our Services
            <br />
            - Personalizing your experience with our Services
            <br />
            - Communicating with you about updates, promotions, and important
            information
            <br />
            - Enhancing the security of our Services
            <br />
            - Conducting analysis and research to improve our Services
            <br />
            <br />
            Data Security
            <br />
            We implement appropriate technical and organizational measures to
            ensure a level of security appropriate to the risk associated with
            the processing of your personal data.
            <br />
            <br />
            Your Rights
            <br />
            You have the right to access, update, delete, or restrict the
            processing of your personal data. If you wish to exercise any of
            these rights, please contact us at [email protected]
            <br />
            <br />
            Changes to This Privacy Policy
            <br />
            We may update this Privacy Policy from time to time. You are advised
            to review this page periodically for any changes.
            <br />
            <br />
            Contact Us
            <br />
            If you have any questions or concerns about this Privacy Policy,
            please dont contact us as this generated as this is generated by
            ChatGpt.
          </Text>
        </Box>
      </FlexBox>
    </CryptoInvestmentTrackerLayout>
  );
};

export default PrivacyPolicy;
